apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: auth-service
build:
  artifacts:
    - image: auth-service
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "app/**/*.py"
            dest: /app
deploy:
  helm:
    releases:
      - name: auth-service
        chartPath: helm/auth-service
        namespace: scholar-spark-dev
        createNamespace: true
        valuesFiles:
          - helm/auth-service/values.yaml
portForward:
  - resourceType: service
    resourceName: auth-service
    namespace: scholar-spark-dev
    port: 8000
    localPort: 8000
