apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: auth-service
build:
  artifacts:
    - image: auth-service
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "app/**/*.py"
            dest: /app
deploy:
  helm:
    releases:
      - name: auth-service
        chartPath: helm
        namespace: scholar-spark-dev
        createNamespace: true
        valuesFiles:
          - helm/values.yaml
        setValueTemplates:
          database.user: "{{.POSTGRES_USER}}"
          database.password: "{{.POSTGRES_PASSWORD}}"
          database.name: "{{.POSTGRES_DB}}"
          jwt.secretKey: "{{.JWT_SECRET_KEY}}"
portForward:
  - resourceType: service
    resourceName: auth-service
    namespace: scholar-spark-dev
    port: 8000
    localPort: 8000
