apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: scholar-spark-dev
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: {{ .Values.database.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.password }}
            - name: POSTGRES_DB
              value: {{ .Values.database.name }}
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: scholar-spark-dev
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  type: ClusterIP 